# Generated by Django 6.1.1 on 2026-10-06 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł gry')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Cena (PLN)')),
                ('release_date', models.DateField(verbose_name='Data premiery')),
                ('players_count', models.IntegerField(verbose_name='Maksymalna liczba graczy')),
                ('description', models.TextField(verbose_name='Opis gry')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='boardgames.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Gra',
                'verbose_name_plural': 'Gry',
                'ordering': ['title'],
            },
        ),
    ]
